// Build the game into one self-contained HTML string and write it where the app
// imports it: apps/mobile/src/features/games/wave-run/html.generated.ts.
//
// The output is committed, so Metro, CI and EAS never run this. CI runs it and
// fails on a diff, which keeps the committed page in step with this source.
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import { embedGame } from '../../game-host/scripts/embed.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

await embedGame({
  build,
  root,
  entry: join(root, 'src/main.ts'),
  out: join(root, '../../apps/mobile/src/features/games/wave-run/html.generated.ts'),
  exportName: 'WAVE_RUN_HTML',
  libName: 'WaveRun',
  header: [
    'GENERATED by packages/wave-run (yarn workspace @skkuverse/wave-run build:embed). Do not edit.',
    'The whole game page — script, styles and skyline art — as one string for the WebView.',
  ],
  css: [
    'html,body{height:100%;margin:0;background:#073e32;overflow:hidden;overscroll-behavior:none;-webkit-tap-highlight-color:transparent;-webkit-text-size-adjust:100%}',
    '#stage{position:relative;width:100%;height:100%;overflow:hidden;touch-action:none;user-select:none;-webkit-user-select:none;-webkit-touch-callout:none}',
    '#canvas{position:absolute;inset:0;width:100%;height:100%;display:block;image-rendering:pixelated}',
  ].join('\n'),
  body: '<div id="stage"><canvas id="canvas"></canvas></div>',
});
