export {
  parseTabsConfig,
  parseNoticePage,
  parseNoticeDetail,
} from './parser';
export type {
  TabDepartment,
  PickerTabConfig,
  FixedTabConfig,
  NoticeTab,
  NoticeTabsConfig,
  Department,
  NoticeSummaryType,
  NoticeStartAt,
  NoticeEndAt,
  NoticeListItem,
  NoticeListItemSummary,
  NoticePage,
  NoticeDetail,
  NoticeDetailSummary,
  NoticeSummaryDetails,
  NoticePeriod,
  NoticeLocation,
  NoticeAttachment,
  NoticeEditInfo,
} from './types';
