// Build the game into one self-contained HTML string and write it where the app
// imports it: apps/mobile/src/features/games/subway-typing/html.generated.ts.
//
// The output is committed, so Metro, CI and EAS never run this. CI runs it and
// fails on a diff, which keeps the committed page in step with this source.
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import { embedGame } from '../../game-host/scripts/embed.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const HANGUL = 'U+1100-11FF,U+3130-318F,U+A960-A97F,U+AC00-D7AF,U+D7B0-D7FF';
const KO_FACES = [
  [400, 'Regular'],
  [500, 'Medium'],
  [600, 'SemiBold'],
  [700, 'Bold'],
].map(([weight, name]) => `@font-face{font-family:KoFallback;src:local('AppleSDGothicNeo-${name}');font-weight:${weight};unicode-range:${HANGUL}}`);

await embedGame({
  build,
  root,
  entry: join(root, 'src/page/main.tsx'),
  out: join(root, '../../apps/mobile/src/features/games/subway-typing/html.generated.ts'),
  exportName: 'SUBWAY_TYPING_HTML',
  libName: 'SubwayTyping',
  header: [
    'GENERATED by packages/subway-typing (yarn workspace @skkuverse/subway-typing build:embed). Do not edit.',
    'The whole game page — React, script, styles and the train — as one string for the WebView.',
  ],
  // Library mode leaves `process.env.NODE_ENV` alone, and React reads it: in a
  // page with no `process` that is a ReferenceError, and left as a variable it
  // would ship React's development build.
  define: { 'process.env.NODE_ENV': '"production"' },
  css: [
    'html,body{height:100%;margin:0;background:#fff;overflow:hidden;overscroll-behavior:none;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:transparent;-webkit-text-size-adjust:100%}',
    // Hangul first, through a face that covers only Hangul: the iOS 26.3
    // simulator's system-font fallback draws Hangul as LastResort boxes, and
    // WebKit never reaches a later family once -apple-system claims the
    // character. On a device this is the font the system picks for Korean
    // anyway, and Latin stays in SF. Elsewhere local() misses and the stack
    // goes on as before.
    ...KO_FACES,
    "body{font-family:KoFallback,-apple-system,BlinkMacSystemFont,'Apple SD Gothic Neo','Noto Sans KR',Roboto,sans-serif}",
    'button{-webkit-appearance:none;appearance:none;cursor:pointer}',
    // The web view lets text be edited (the input); nothing else may be selected by a long press.
    'body{-webkit-user-select:none;user-select:none;-webkit-touch-callout:none}',
    'input{-webkit-user-select:text;user-select:text}',
  ].join('\n'),
  body: '<div id="root"></div>',
});
